export { default as Prefix } from './src/decorators/Prefix';
export { default as ReqOpt } from './src/Options';
export { default as Headers } from './src/decorators/Headers';
export { default as BodyType } from './src/decorators/BodyType';
export { default as Before } from './src/decorators/Before';
export { default as After } from './src/decorators/After';
export { default as Err } from './src/decorators/Error';
export { default as Extension } from './src/decorators/Extension';
export { default as JSONPCallbackPrefix } from './src/decorators/JSONPCallbackPrefix';
export { default as JSONPCallbackParam } from './src/decorators/JSONPCallbackParam';
export { default as Adapter } from './src/decorators/Adapter';
export { useAdapter as useAdapter } from './src/Request';
export { Get as Get, Post as Post, Patch as Patch, Put as Put, Delete as Delete, JSONP as JSONP, } from './src/decorators/Methods';
declare const _default: {};
export default _default;
